import openai
import os
from dotenv import load_dotenv
import os


def set_api_key() -> None:
    '''Set OpenAI api key'''
    load_dotenv()
    # get env variable
    openai.api_key = os.environ.get("API_KEY")


def send_prompt(prompt: str, model: str = "gpt-3.5-turbo") -> str:
    """
    Sends a prompt to the OpenAI chat model and returns the response.
    
    Args:
    - prompt (str): The prompt to send to the chat model.
    - model (str): The ID of the OpenAI chat model to use.
    
    Returns:
    - The response generated by the chat model as a string.
    """
    response = openai.ChatCompletion.create(
        model=model,
        messages=[
            {"role": "system", "content": "You are an AI assistant to help sellers improve their products given customer complaints."},
            {"role": "user", "content": prompt}
        ]
        )
    return response['choices'][0]['message']['content']